namespace AiPixelScaler.Desktop.Views.Studios;

public enum SpriteStudioAction
{
    OpenImage,
    ApplyDefaultPreset,
    ApplySafePreset,
    ApplyAggressivePreset,
    RunCleanup,
    RunOneClickCleanup,
    ApplyPipeline,
    ApplyDefringe,
    ApplyMedian,
    ApplyEdgeBackground,
    ApplyDenoise,
    SelectArea,
    SelectAll,
    ClearSelection,
    ExportSelection,
    CropSelection,
    RemoveSelection,
    ToggleManualCrop,
    DetectSprites,
    GridSlice,
    SaveSelectedFrame,
    OpenFloatingPaste,
    PasteDestination,
    PasteSource,
    CopyPasteSelection,
    ExitFloatingPaste,
    ApplyQuantize,
    MirrorHorizontal,
    MirrorVertical,
    ResizeNearest,
    ExportPng,
    ExportJson
}
